version: "3.8"
services:

  server:
    image: aruco-webapp:server
    # build:
    #   context: .
    #   dockerfile: Dockerfile.server
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - $PWD/aruco-webapp
      - /tmp/.X11-unix:/tmp/.X11-unix
    user: user
    devices: 
      - /dev/video0:/dev/video0
    network_mode: host

  client:
    image: aruco-webapp:client
    # build:
    #   context: .
    #   dockerfile: Dockerfile.client
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - $PWD/aruco-webapp
      - /tmp/.X11-unix:/tmp/.X11-unix
    user: user
    devices: 
      - /dev/video0:/dev/video0
    network_mode: host