FROM opencvcourses/opencv-docker:latest

RUN adduser --disabled-password --gecos '' user
RUN usermod -aG video user

ENV LD_LIBRARY_PATH=/usr/local/lib

RUN apt-get update &&  apt-get install -y libgl1-mesa-glx
COPY --chown=user . /home/aruco-webapp/
RUN pip3 install -r /home/aruco-webapp/requirements.txt

WORKDIR /home/aruco-webapp/client
CMD ["python3","run_client.py"]
